<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="6" tests="51" name="testCases.Stack" time="431.946" errors="0" timestamp="2025-08-15T10:14:31 GMT-04:00" skipped="18">
  <testcase classname="testCases.Stack" name="open_stac_page" time="6.711"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="4.431"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="6.067"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="8.569"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="5.937"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="7.156"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="7.047"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="9.054"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="7.085"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.120">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.467">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.264">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="8.647">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="15.261">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="9.857">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="9.584">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.735">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.345">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.105">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="8.081">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="16.739">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="9.239"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="9.018"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="15.292"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="7.950"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="7.841"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="7.322"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="4.933"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="12.436"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="5.898"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="14.173"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="7.830"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="7.575"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="7.950"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="7.528"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="6.423"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="7.415"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="16.271"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="7.171"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="6.930">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.075">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.635">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="9.090">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="14.902">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="8.189">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackopenPracticeQuestions(Stack.java:148)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="6.944">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.771">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.051">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.410">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.567">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackopenPracticeQuestions(Stack.java:148)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="4.855">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackopenPracticeQuestions(Stack.java:148)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
</testsuite> <!-- testCases.Stack -->
