<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="6" tests="51" name="testCases.StackTest" time="359.407" errors="0" timestamp="2025-08-17T00:39:27 GMT-04:00" skipped="18">
  <testcase classname="testCases.StackTest" name="open_stac_page" time="4.764"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="open_stac_page" time="9.133"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="open_stac_page" time="4.446"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackOperations" time="5.676"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackOperations" time="5.200"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackOperations" time="9.397"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackoperationsCodeEditor" time="6.525"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackoperationsCodeEditor" time="7.145"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackoperationsCodeEditor" time="6.979"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="7.688">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="6.671">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="6.574">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.StackTest.StackTryingEmptyEditor(StackTest.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="6.641">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="6.544">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="10.253">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.StackTest.StackTryingEmptyEditor(StackTest.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="5.880">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="5.790">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="6.710">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="6.005">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="12.417">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingEmptyEditor" time="6.885">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.StackTest.StackTryingEmptyEditor(StackTest.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingValidAndInvalidCode" time="5.848"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingValidAndInvalidCode" time="6.680"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingValidAndInvalidCode" time="6.568"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingValidAndInvalidCode" time="10.243"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingValidAndInvalidCode" time="5.489"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackTryingValidAndInvalidCode" time="12.741"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackimplementation" time="4.855"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackimplementation" time="6.301"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackimplementation" time="5.665"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackimplementationCodeEditor" time="7.221"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackimplementationCodeEditor" time="6.108"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackimplementationCodeEditor" time="6.051"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackapplication" time="6.275"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackapplication" time="5.188"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackapplication" time="10.289"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackapplicationCodeEditor" time="6.686"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackapplicationCodeEditor" time="10.610"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="stackapplicationCodeEditor" time="5.675"/>
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="5.340">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="9.789">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="6.433">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.StackTest.StackopenPracticeQuestions(StackTest.java:160)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="5.567">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="6.316">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="11.214">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="6.809">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.StackTest.StackopenPracticeQuestions(StackTest.java:160)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="6.611">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="6.452">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="6.693">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="6.074">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.StackTest" name="StackopenPracticeQuestions" time="6.293">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.StackTest.StackopenPracticeQuestions(StackTest.java:160)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
</testsuite> <!-- testCases.StackTest -->
