<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-181TTAT" failures="6" tests="51" name="testCases.Stack" time="438.470" errors="0" timestamp="2025-08-17T00:11:45 GMT-04:00" skipped="18">
  <testcase classname="testCases.Stack" name="open_stac_page" time="8.594"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="6.839"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="open_stac_page" time="7.748"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="6.114"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="7.186"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackOperations" time="9.539"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="7.503"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="6.398"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackoperationsCodeEditor" time="14.046"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="9.320">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.120">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="6.990">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="13.664">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="8.023">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="8.270">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="6.788">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="7.353">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="9.015">
    <failure message="Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is, no alert message comes up when clicking on run button without entering anhy code in it
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackTryingEmptyEditor(Stack.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="13.414">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="13.665">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingEmptyEditor" time="9.755">
    <skipped/>
  </testcase> <!-- StackTryingEmptyEditor -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="7.080"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="6.736"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="11.147"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="8.422"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="9.727"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackTryingValidAndInvalidCode" time="8.446"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="9.344"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="7.857"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementation" time="8.310"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="11.311"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="7.045"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackimplementationCodeEditor" time="6.492"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="6.975"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="13.593"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplication" time="6.033"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="9.097"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="6.263"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="stackapplicationCodeEditor" time="6.168"/>
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="8.541">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="5.620">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.237">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackopenPracticeQuestions(Stack.java:160)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.765">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="8.814">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="12.473">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="6.602">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="6.980">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="9.244">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackopenPracticeQuestions(Stack.java:160)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="13.602">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="7.677">
    <failure message="Failing this test case to show the bug which is,there are no practice questions available for stack module" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing this test case to show the bug which is,there are no practice questions available for stack module
at org.testng.Assert.fail(Assert.java:110)
at testCases.Stack.StackopenPracticeQuestions(Stack.java:160)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
  <testcase classname="testCases.Stack" name="StackopenPracticeQuestions" time="6.525">
    <skipped/>
  </testcase> <!-- StackopenPracticeQuestions -->
  <system-out/>
</testsuite> <!-- testCases.Stack -->
